CREATE USER IF NOT EXISTS '__DB_USER__'@'%' IDENTIFIED BY '__DB_PASSWORD__';

REVOKE ALL PRIVILEGES, GRANT OPTION FROM '__DB_USER__'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE
    ON __DB_NAME__.*
    TO '__DB_USER__'@'%';

REVOKE CREATE, DROP, ALTER, INDEX
    ON __DB_NAME__.*
    FROM '__DB_USER__'@'%';

FLUSH PRIVILEGES;
