services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 10s
      retries: 10

  db-init:
    image: mysql:8.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: >
      sh -c "
        if mysql -h db -P ${DB_PORT} -u root -p${DB_ROOT_PASSWORD} -e 'USE ${DB_NAME}; SHOW TABLES;' 2>/dev/null | grep -q .; then
          echo 'Database already initialized. Skipping init scripts.'
          exit 0
        fi

        sed 's/__DB_NAME__/${DB_NAME}/g' /sql/create_db.sql | mysql -h db -P ${DB_PORT} -u root -p${DB_ROOT_PASSWORD}

        sed -e 's/__DB_NAME__/${DB_NAME}/g' -e 's/__DB_USER__/${DB_USER}/g' -e 's/__DB_PASSWORD__/${DB_PASSWORD}/g' /sql/create_user.sql | mysql -h db -P ${DB_PORT} -u root -p${DB_ROOT_PASSWORD} ${DB_NAME}

        mysql -h db -P ${DB_PORT} -u root -p${DB_ROOT_PASSWORD} ${DB_NAME} < sql/create_event.sql
      "

    volumes:
      - ${DB_INIT_SQL_PATH}:/sql:ro

  server:
    image: openchatroom-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      # Environment setup
      - ConnectionStrings__DefaultConnection=server=db;port=${DB_PORT};user=${DB_USER};password=${DB_PASSWORD};database=${DB_NAME}
      - ASPNETCORE_ENVIRONMENT=Production
      # JWT parameters
      - Jwt__KeyFile=/app/jwt-key.txt
      - Jwt__Authority=${JwtAuthority}
      - Jwt__Audience=${JwtAudience}
      - Jwt__Issuer=${JwtIssuer}
      - Jwt__LifeTimeMinutes=${JwtLifetimeMinutes}
      # Encryptor
      - Encryptor__KeyFile=/app/message-key.txt
      # User Config info
      - UserConfig__MessageCountPerRequest=${MessageCountPerRequest}
      - UserConfig__ChannelCountPerRequest=${ChannelCountPerRequest}
      # HTTPS server info
      - ASPNETCORE_URLS=https://+:${APP_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/openchatroom.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
    volumes:
      - ${CERT_PATH}:/app/openchatroom.pfx:ro
      - ${JWT_KEY_PATH}:/app/jwt-key.txt
      - ${MESSAGE_KEY_PATH}:/app/message-key.txt

volumes:
  db-data:
